# Generated by Django 2.2.4 on 2021-04-01 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0004_auto_20210401_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='')),
                ('about_flat', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='flat_complaints', to='property.Flat')),
                ('from_who', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_complaints', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
