# Generated by Django 2.2.4 on 2021-04-01 13:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0006_auto_20210401_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='likes',
            field=models.ManyToManyField(default=None, related_name='from_users', to=settings.AUTH_USER_MODEL, verbose_name='Кто лайкнул'),
        ),
    ]
