# Generated by Django 2.2.4 on 2021-04-03 12:08

from django.db import migrations


def move_owners_from_flat_to_separate_model(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for flat in Flat.objects.all():
        Owner.objects.get_or_create(
            name=flat.owner,
            phonenumber=flat.owners_phonenumber,
            standartized_phonenumber=flat.owner_standartized_phonenumber,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_owner'),
    ]

    operations = [
        migrations.RunPython(move_owners_from_flat_to_separate_model)
    ]
